INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Laptop', 999.99);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Smartphone', 499.99);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Tablet', 299.99);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Headphones', 149.99);
INSERT INTO PRODUCT (NAME, PRICE) VALUES ('Smartwatch', 249.99);